[package]
name = "rollup-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
paste = "1"
thiserror = "1"

uuid = { version = "1.6.1" }
sha2 = "0.10.0"
chrono = "^0.4"
bytemuck = "1.13.0"
borsh = "1"

serde = {version = "1"}
serde_derive = "1"
serde_json = { version = "1.0.81", features = ["raw_value"] }
serde_with = "3.7.0"
anchor-lang = "0.29.0"

num-derive = "0.4.1"
num-traits = "0.2.17"
schemars = "0.8.6"

solana-sdk = "~1.18.1"
solana-program = "~1.18.1"
solana-client = "~1.18.1"
solana-rpc-client-api = "~1.18.1"

bubblegum = { path = "../mpl-bubblegum/programs/bubblegum/program"}
mpl-bubblegum = { path = "../mpl-bubblegum/clients/rust", features = ["serde"]}
spl-account-compression = { path = "../mpl-bubblegum/solana-program-library/account-compression/programs/account-compression", features = ["no-entrypoint", "cpi"] }
spl-concurrent-merkle-tree = { path = "../mpl-bubblegum/solana-program-library/libraries/concurrent-merkle-tree", default-features = false} 
spl-merkle-tree-reference = { path = "../mpl-bubblegum/solana-program-library/libraries/merkle-tree-reference" }
spl-token = {path = "../mpl-bubblegum/solana-program-library/token/program", features = ["no-entrypoint"]}
spl-noop = { path="../mpl-bubblegum/solana-program-library/account-compression/programs/noop", features = ["no-entrypoint"] }
#voter-stake-registry = { path="../mpl-bubblegum/mplx-staking/programs/voter-stake-registry"}
mplx-staking-states = { path="../mpl-bubblegum/mplx-staking/program-states"}

[dev-dependencies]
tokio = "1"
solana-program-test = "~1.18.1"
mpl-token-metadata = "3.2.3"
mpl-token-auth-rules = { path = "../mpl-bubblegum/mpl-token-auth-rules/programs/token-auth-rules/", features = ["no-entrypoint"] }
spl-associated-token-account = { version = ">= 1.1.3, < 3.0", features = ["no-entrypoint"] }