[package]
name = "rollup-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
paste = "1"
thiserror = "1"

uuid = { version = "1.6" }
sha2 = "0.10"
chrono = "^0.4"
bytemuck = "1.13"
borsh = "1"

serde = {version = "1"}
serde_derive = "1"
serde_json = { version = "1", features = ["raw_value"] }
serde_with = "3.7"
anchor-lang = "0.29.0"

solana-sdk = "~1.18"
solana-program = "~1.18"
solana-client = "~1.18"
solana-rpc-client-api = "~1.18"

bubblegum = { path = "../mpl-bubblegum/programs/bubblegum/program"}
mpl-bubblegum = { path = "../mpl-bubblegum/clients/rust", features = ["serde"]}
spl-account-compression = { path = "../mpl-bubblegum/solana-program-library/account-compression/programs/account-compression", features = ["no-entrypoint", "cpi"] }
spl-concurrent-merkle-tree = { path = "../mpl-bubblegum/solana-program-library/libraries/concurrent-merkle-tree", default-features = false} 
spl-merkle-tree-reference = { path = "../mpl-bubblegum/solana-program-library/libraries/merkle-tree-reference" }
spl-noop = { version = "0.2.0", features = [ "no-entrypoint" ]}
mplx-staking-states = { path="../mpl-bubblegum/mplx-staking/program-states"}

[dev-dependencies]
tokio = "1"
base64 = "0.22"
serial_test = "3"