[package]
name = "metagrid-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1"
thiserror = "1"

uuid = { version = "1.6.1" }
sha2 = "0.10.0"
chrono = "^0.4"

serde = {version = "1"}
serde_derive = "1"
serde_json = { version = "1.0.81", features = ["raw_value"] }
serde_with = "3.7.0"
anchor-lang = "0.29.0"

num-derive = "0.4.1"
num-traits = "0.2.17"
schemars = "0.8.6"

solana-sdk = "~1.18.1"
solana-program = "~1.18.1"
solana-client = "~1.18.1"
solana-rpc-client-api = "~1.18.1"

# While in development: https://github.com/n00m4d/mpl-bubblegum/tree/feature/cleanup
bubblegum = { path = "../mpl-bubblegum/programs/bubblegum/program"}
mpl-bubblegum = { path = "../mpl-bubblegum/clients/rust", features = ["serde"]}
spl-account-compression = { path = "../mpl-bubblegum/solana-program-library/account-compression/programs/account-compression", features = ["no-entrypoint", "cpi"] }
spl-concurrent-merkle-tree = { path = "../mpl-bubblegum/solana-program-library/libraries/concurrent-merkle-tree" } 
spl-merkle-tree-reference = { path = "../mpl-bubblegum/solana-program-library/libraries/merkle-tree-reference" }
spl-token = {path = "../mpl-bubblegum/solana-program-library/token/program"}
spl-noop = { path="../mpl-bubblegum/solana-program-library/account-compression/programs/noop", features = ["no-entrypoint"] }
mplx-staking-states = { path="../mpl-bubblegum/mplx-staking/program-states"}
